wip

diff --git a/utils/build-script-impl b/utils/build-script-impl
--- a/utils/build-script-impl
+++ b/utils/build-script-impl
@@ -257,6 +257,7 @@ components=(
   static-foundation
   static-libdispatch
   swift
+  swiftstdlib
   xctest
 )
 for component in ${components[@]} ; do
@@ -1040,6 +1041,7 @@ function get_stdlib_targets_for_host() {
 #
 NINJA_SOURCE_DIR="${WORKSPACE}/ninja"
 SWIFT_SOURCE_DIR="${WORKSPACE}/swift"
+SWIFTSTDLIB_SOURCE_DIR="${WORKSPACE}/swift/stdlib"
 LLVM_SOURCE_DIR="${WORKSPACE}/llvm-project/llvm"
 CMARK_SOURCE_DIR="${WORKSPACE}/cmark"
 LLDB_SOURCE_DIR="${WORKSPACE}/llvm-project/lldb"
@@ -1058,6 +1060,7 @@ LIBCXX_SOURCE_DIR="${WORKSPACE}/llvm-project/libcxx"
 [[ "${SKIP_BUILD_LIBICU}" ]] || PRODUCTS+=(libicu)
 [[ "${SKIP_BUILD_LLVM}" ]] || PRODUCTS+=(llvm)
 [[ "${SKIP_BUILD_SWIFT}" ]] || PRODUCTS+=(swift)
+PRODUCTS+=(swiftstdlib)
 [[ "${SKIP_BUILD_LLDB}" ]] || PRODUCTS+=(lldb)
 [[ "${SKIP_BUILD_LIBDISPATCH}" ]] || PRODUCTS+=(libdispatch)
 [[ "${SKIP_BUILD_STATIC_LIBDISPATCH}" ]] || PRODUCTS+=(libdispatch_static)
@@ -1560,7 +1563,7 @@ for host in "${ALL_HOSTS[@]}"; do
 
                 ;;
 
-            swift)
+            swift|swiftstdlib)
 
                 if [[ "${ANDROID_API_LEVEL}" ]]; then
                     cmake_options=(
@@ -1599,16 +1602,18 @@ for host in "${ALL_HOSTS[@]}"; do
                 native_llvm_tools_path=""
                 native_clang_tools_path=""
                 native_swift_tools_path=""
+                if [[ ${product} = swiftstdlib || $(is_cross_tools_host ${host}) ]]; then
+                    native_llvm_tools_path="$(build_directory "${LOCAL_HOST}" llvm)/bin"
+                    native_clang_tools_path="$(build_directory "${LOCAL_HOST}" llvm)/bin"
+                    native_swift_tools_path="$(build_directory "${LOCAL_HOST}" swift)/bin"
+                fi
+
                 if [[ $(is_cross_tools_host ${host}) ]] ; then
 
                     # Don't build benchmarks and tests when building cross compiler.
                     build_perf_testsuite_this_time=false
                     build_external_perf_testsuite_this_time=false
                     build_tests_this_time=false
-
-                    native_llvm_tools_path="$(build_directory "${LOCAL_HOST}" llvm)/bin"
-                    native_clang_tools_path="$(build_directory "${LOCAL_HOST}" llvm)/bin"
-                    native_swift_tools_path="$(build_directory "${LOCAL_HOST}" swift)/bin"
                 else
                     # FIXME: Why is the next line not using false_true?
                     build_perf_testsuite_this_time=$(true_false "$(not ${SKIP_BUILD_BENCHMARKS})")
@@ -1670,6 +1675,7 @@ for host in "${ALL_HOSTS[@]}"; do
                     -DSWIFT_NATIVE_LLVM_TOOLS_PATH:STRING="${native_llvm_tools_path}"
                     -DSWIFT_NATIVE_CLANG_TOOLS_PATH:STRING="${native_clang_tools_path}"
                     -DSWIFT_NATIVE_SWIFT_TOOLS_PATH:STRING="${native_swift_tools_path}"
+                    -DSWIFT_COMPILER_BUILD_DIR="$(build_directory "${LOCAL_HOST}" swift)"
                     -DSWIFT_INCLUDE_TOOLS:BOOL=$(true_false "${BUILD_SWIFT_TOOLS}")
                     -DSWIFT_BUILD_REMOTE_MIRROR:BOOL=$(true_false "${BUILD_SWIFT_REMOTE_MIRROR}")
                     -DSWIFT_STDLIB_SIL_DEBUGGING:BOOL=$(true_false "${BUILD_SIL_DEBUGGING_STDLIB}")
@@ -1751,16 +1757,27 @@ for host in "${ALL_HOSTS[@]}"; do
                     )
                 fi
 
-                build_targets=(all "${SWIFT_STDLIB_TARGETS[@]}")
-                if [[ $(true_false "${build_perf_testsuite_this_time}") == "TRUE" ]]; then
-                    native_swift_tools_path="$(build_directory_bin ${LOCAL_HOST} swift)"
-                    cmake_options=(
-                        "${cmake_options[@]}"
-                        -DSWIFT_EXEC:STRING="${native_swift_tools_path}/swiftc"
-                    )
-                    build_targets=("${build_targets[@]}"
-                                   "${SWIFT_BENCHMARK_TARGETS[@]}")
-                fi
+                case ${product} in
+                    swift)
+                        build_targets=(all)
+                        ;;
+                    swiftstdlib)
+                        build_targets=("${SWIFT_STDLIB_TARGETS[@]}")
+                        if [[ $(true_false "${build_perf_testsuite_this_time}") == "TRUE" ]]; then
+                            native_swift_tools_path="$(build_directory_bin ${LOCAL_HOST} swift)"
+                            cmake_options=(
+                                "${cmake_options[@]}"
+                                -DSWIFT_EXEC:STRING="${native_swift_tools_path}/swiftc"
+                            )
+                            build_targets=("${build_targets[@]}"
+                                           "${SWIFT_BENCHMARK_TARGETS[@]}")
+                        fi
+                        ;;
+                    *)
+                        echo "error: unknown product: ${product}"
+                        exit 1
+                        ;;
+                esac
                 ;;
             lldb)
                 if [ ! -d "${LLDB_SOURCE_DIR}" ]; then
@@ -2321,7 +2338,6 @@ for host in "${ALL_HOSTS[@]}"; do
                 results_targets=
                 if ! [[ "${SKIP_TEST_SWIFT}" ]]; then
                     executable_target=SwiftUnitTests
-                    results_targets=("${SWIFT_TEST_TARGETS[@]}")
                     if [[ "${STRESS_TEST_SOURCEKIT}" ]]; then
                         results_targets=(
                             "${results_targets[@]}"
@@ -2329,11 +2345,19 @@ for host in "${ALL_HOSTS[@]}"; do
                         )
                     fi
                 fi
-                if ! [[ "${SKIP_TEST_BENCHMARKS}" ]]; then
-                    results_targets=(
-                        "${results_targets[@]}"
-                        "${SWIFT_RUN_BENCHMARK_TARGETS[@]}"
-                    )
+                if [[ -z "${results_targets[@]}" ]]; then
+                    continue
+                fi
+                ;;
+            swiftstdlib)
+                if ! [[ "${SKIP_TEST_SWIFT}" ]]; then
+                    results_targets=("${SWIFT_TEST_TARGETS[@]}")
+                    if ! [[ "${SKIP_TEST_BENCHMARKS}" ]]; then
+                        results_targets=(
+                            "${results_targets[@]}"
+                            "${SWIFT_RUN_BENCHMARK_TARGETS[@]}"
+                        )
+                    fi
                 fi
                 if [[ -z "${results_targets[@]}" ]]; then
                     continue
@@ -2655,7 +2679,7 @@ for host in "${ALL_HOSTS[@]}"; do
                 fi
                 INSTALL_TARGETS=install-cxx-headers
                 ;;
-            swift)
+            swift|swiftstdlib)
                 if [[ -z "${INSTALL_SWIFT}" ]] ; then
                     continue
                 fi
